//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessfile
    {
        public Accessfile()
        {
            this.MenubaseAccesses = new HashSet<MenubaseAccess>();
        }
    
        public System.Guid RecId { get; set; }
        public string SysCode { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ChildId { get; set; }
        public bool AllowAdd { get; set; }
        public bool AllowEdit { get; set; }
        public bool AllowDelete { get; set; }
        public bool AllowPost { get; set; }
        public bool AllowUnpost { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual Menubase Menubase { get; set; }
        public virtual ICollection<MenubaseAccess> MenubaseAccesses { get; set; }
    }
}
