//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCodeItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AccountCodeId { get; set; }
        public Nullable<System.Guid> ItemTypeId { get; set; }
        public Nullable<System.Guid> ItemCodeId { get; set; }
        public string Code { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual AccountCode AccountCode { get; set; }
        public virtual ItemCode ItemCode { get; set; }
        public virtual ItemType ItemType { get; set; }
    }
}
