//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIR()
        {
            this.AIRInvoices = new HashSet<AIRInvoice>();
            this.AIRItems = new HashSet<AIRItem>();
            this.AIRDocuments = new HashSet<AIRDocument>();
            this.AIRSubmissionSnapshots = new HashSet<AIRSubmissionSnapshot>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public string AIRNo { get; set; }
        public Nullable<System.DateTime> AIRDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<bool> IsPartial { get; set; }
        public string Custodian { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> InspectedDate { get; set; }
        public Nullable<bool> IsInspected { get; set; }
        public string Officer { get; set; }
        public string InvDist { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public string CtrlNo { get; set; }
        public string InspectionStatus { get; set; }
        public string AcceptanceStatus { get; set; }
        public string OverallStatus { get; set; }
        public string DrNo { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public string InvoiceType { get; set; }
        public string BillingReference { get; set; }
        public string InspectionLocation { get; set; }
        public string InspectorName { get; set; }
        public string InspectorDesignation { get; set; }
        public string InspectionCommittee { get; set; }
        public string AcceptanceStartedBy { get; set; }
        public Nullable<System.DateTime> AcceptanceStartedDt { get; set; }
        public string AcceptedBy { get; set; }
        public string AcceptedByDesignation { get; set; }
        public string AcceptanceRemarks { get; set; }
        public bool WithdrawalRequested { get; set; }
        public string WithdrawalRequestedBy { get; set; }
        public Nullable<System.DateTime> WithdrawalRequestedDt { get; set; }
        public string WithdrawalReason { get; set; }
        public string RevisionComments { get; set; }
        public string ReturnedBy { get; set; }
        public Nullable<System.DateTime> ReturnedDt { get; set; }
        public string WithdrawnBy { get; set; }
        public Nullable<System.DateTime> WithdrawnDt { get; set; }
        public string Disposition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRInvoice> AIRInvoices { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRItem> AIRItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRDocument> AIRDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRSubmissionSnapshot> AIRSubmissionSnapshots { get; set; }
    }
}
