//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRDocument
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AirId { get; set; }
        public string DocumentType { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileSize { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UploadedDt { get; set; }
    
        public virtual AIR AIR { get; set; }
    }
}
