//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRItemExtn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIRItemExtn()
        {
            this.PsCardItemExtns = new HashSet<PsCardItemExtn>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AIRItemId { get; set; }
        public string SetLotNo { get; set; }
        public Nullable<int> SetLotQtyNo { get; set; }
        public Nullable<int> ContentNo { get; set; }
        public Nullable<int> CustItemNo { get; set; }
        public Nullable<bool> IsAutoGen { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<int> TContentNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemExtn> PsCardItemExtns { get; set; }
        public virtual AIRItem AIRItem { get; set; }
    }
}
