//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIRItem()
        {
            this.AIRItemExtns = new HashSet<AIRItemExtn>();
            this.AIRItemAllocations = new HashSet<AIRItemAllocation>();
            this.AIRSubItems = new HashSet<AIRSubItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AirId { get; set; }
        public Nullable<System.Guid> OrderItemRequestId { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> AreaSoldDonated { get; set; }
        public Nullable<int> ConstructionYear { get; set; }
        public string InvDist { get; set; }
        public Nullable<bool> IsForICS { get; set; }
        public Nullable<bool> IsConsumable { get; set; }
        public Nullable<bool> IsIncorporated { get; set; }
        public Nullable<bool> IsOthers { get; set; }
        public string OthersRemarks { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<decimal> InspectedQty { get; set; }
        public Nullable<decimal> AcceptedQty { get; set; }
        public string Disposition { get; set; }
        public string DestinationDepartment { get; set; }
        public string DestinationCustodian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRItemExtn> AIRItemExtns { get; set; }
        public virtual AIR AIR { get; set; }
        public virtual OrderItemRequest OrderItemRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRItemAllocation> AIRItemAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRSubItem> AIRSubItems { get; set; }
    }
}
