//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRItemAllocation
    {
        public System.Guid Id { get; set; }
        public System.Guid AIRItemId { get; set; }
        public System.Guid OrderItemRequestId { get; set; }
        public decimal QtyAllocated { get; set; }
        public decimal QtyInspected { get; set; }
        public string PRNumber { get; set; }
        public string Department { get; set; }
        public string Remarks { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual AIRItem AIRItem { get; set; }
        public virtual OrderItemRequest OrderItemRequest { get; set; }
    }
}
