//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRSubItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIRSubItem()
        {
            this.AIRItemExtns = new HashSet<AIRItemExtn>();
            this.PsCardSubItems = new HashSet<PsCardSubItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid AirItemId { get; set; }
        public Nullable<System.Guid> OrderSubItemId { get; set; }
        public Nullable<System.Guid> OrderSubItemRequestId { get; set; }
        public string SubItemNo { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public decimal ExpectedQty { get; set; }
        public decimal InspectedQty { get; set; }
        public decimal AcceptedQty { get; set; }
        public string Remarks { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<decimal> QtyPerParent { get; set; }
        public string CategoryCode { get; set; }
        public string ItemExtnName { get; set; }
        public Nullable<System.Guid> ItemCodeId { get; set; }
        public string SourceType { get; set; }
        public Nullable<bool> IsRequiredForBundle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRItemExtn> AIRItemExtns { get; set; }
        public virtual AIRItem AIRItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardSubItem> PsCardSubItems { get; set; }
    }
}
