//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRSubmissionSnapshot
    {
        public System.Guid Id { get; set; }
        public System.Guid AIRId { get; set; }
        public Nullable<System.Guid> WizardProgressId { get; set; }
        public int VersionNo { get; set; }
        public string PayloadJson { get; set; }
        public string SubmittedBy { get; set; }
        public System.DateTime SubmittedDt { get; set; }
        public System.DateTime CreatedDt { get; set; }
    
        public virtual AIR AIR { get; set; }
        public virtual AIRWizardProgress AIRWizardProgress { get; set; }
    }
}
