//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRWizardProgress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIRWizardProgress()
        {
            this.AIRSubmissionSnapshots = new HashSet<AIRSubmissionSnapshot>();
        }
    
        public System.Guid Id { get; set; }
        public string DraftNo { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int LastStep { get; set; }
        public string WizardStateJson { get; set; }
        public bool IsCompleted { get; set; }
        public string UserId { get; set; }
        public string Status { get; set; }
        public int CurrentStep { get; set; }
        public Nullable<System.Guid> AIRId { get; set; }
        public Nullable<System.Guid> SourceAIRId { get; set; }
        public int RevisionNo { get; set; }
        public Nullable<System.DateTime> SubmittedDt { get; set; }
        public Nullable<System.DateTime> DiscardedDt { get; set; }
        public string DiscardedBy { get; set; }
        public string DiscardedReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRSubmissionSnapshot> AIRSubmissionSnapshots { get; set; }
    }
}
