//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllField
    {
        public System.Guid Id { get; set; }
        public string AcqMode { get; set; }
        public string InvDist { get; set; }
        public string GenericName { get; set; }
        public string DosageStrength { get; set; }
        public string DosageForm { get; set; }
        public string DosageVolume { get; set; }
        public string Others { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Multipliers { get; set; }
        public string Model_ { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Barangay { get; set; }
        public Nullable<System.DateTime> DateSale { get; set; }
        public Nullable<System.DateTime> DateDonation { get; set; }
        public Nullable<System.DateTime> DateAcquisition { get; set; }
        public Nullable<System.DateTime> DateConstruction { get; set; }
        public Nullable<decimal> AreaSoldDonated { get; set; }
        public Nullable<decimal> PricePerSqm { get; set; }
        public Nullable<decimal> AcqCost { get; set; }
        public string VendorDonor { get; set; }
        public string Type { get; set; }
        public string Dimension { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
        public string Materials { get; set; }
        public string Capacity { get; set; }
        public string Color { get; set; }
        public string SerialNo { get; set; }
        public string PropNo { get; set; }
        public string PlateNo { get; set; }
        public string BodyNo { get; set; }
        public string MVFileNo { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual PsCard PsCard { get; set; }
        public virtual Procurement Procurement { get; set; }
        public virtual ProcurementItem ProcurementItem { get; set; }
        public virtual RisItem RisItem { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
