//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllField
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RisItemId { get; set; }
        public Nullable<System.Guid> PsCardId { get; set; }
        public string AcqMode { get; set; }
        public string InvDist { get; set; }
        public string GenericName { get; set; }
        public string DosageStrength { get; set; }
        public string DosageForm { get; set; }
        public string DosageVolume { get; set; }
        public string Others { get; set; }
        public string Brand { get; set; }
        public string Model_ { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Barangay { get; set; }
        public Nullable<System.DateTime> DateSale { get; set; }
        public Nullable<System.DateTime> DateDonation { get; set; }
        public Nullable<System.DateTime> DateAcquisition { get; set; }
        public Nullable<System.DateTime> DateConstruction { get; set; }
        public Nullable<decimal> AreaSoldDonated { get; set; }
        public Nullable<decimal> PricePerSqm { get; set; }
        public Nullable<decimal> AcqCost { get; set; }
        public string VendorDonor { get; set; }
        public string TctNo { get; set; }
        public string PhaseNo { get; set; }
        public Nullable<decimal> PhaseAmount { get; set; }
        public string Type { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> YearModel { get; set; }
        public string NetWeight { get; set; }
        public string ConductionSticker { get; set; }
        public string PlateNo { get; set; }
        public string BodyNo { get; set; }
        public string CRN { get; set; }
        public Nullable<System.DateTime> CRNDate { get; set; }
        public string MVFileNo { get; set; }
        public string Dimension { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
        public string Materials { get; set; }
        public string Capacity { get; set; }
        public string Color { get; set; }
        public string PropertyNo { get; set; }
        public string DRPNo { get; set; }
        public Nullable<System.DateTime> DRPDate { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> CGT { get; set; }
        public Nullable<decimal> CGTTransferTax { get; set; }
        public Nullable<decimal> CGTSurcharge { get; set; }
        public Nullable<decimal> CGTInterest { get; set; }
        public Nullable<decimal> CGTCompromise { get; set; }
        public Nullable<decimal> DST { get; set; }
        public Nullable<decimal> DSTTransferTax { get; set; }
        public Nullable<decimal> DSTSurcharge { get; set; }
        public Nullable<decimal> DSTInterest { get; set; }
        public Nullable<decimal> DSTCompromise { get; set; }
        public Nullable<decimal> TransferTax { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> ConfirmationFee { get; set; }
        public Nullable<decimal> TransferRegsFee { get; set; }
        public Nullable<decimal> RealPropertyTax { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> EstateTax { get; set; }
        public Nullable<decimal> Tilting { get; set; }
        public Nullable<decimal> CertificationFee { get; set; }
        public Nullable<decimal> Relocation { get; set; }
        public Nullable<decimal> Surveying { get; set; }
        public Nullable<decimal> IncidentalExpenses { get; set; }
        public string CapitalOutlyOrExpense { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual PsCard PsCard { get; set; }
        public virtual RisItem RisItem { get; set; }
    }
}
