//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppManEntities : DbContext
    {
        public AppManEntities()
            : base("name=AppManEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menubase> Menubases { get; set; }
        public virtual DbSet<AspNetUserRoles_View> AspNetUserRoles_View { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<UserCodes_View> UserCodes_View { get; set; }
        public virtual DbSet<UserCode> UserCodes { get; set; }
        public virtual DbSet<UserInfo> UserInfos { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<AspNetUsers_View> AspNetUsers_View { get; set; }
        public virtual DbSet<CodeMast> CodeMasts { get; set; }
        public virtual DbSet<MenuAccess> MenuAccesses { get; set; }
        public virtual DbSet<MenuAccessAction> MenuAccessActions { get; set; }
        public virtual DbSet<MenuAction> MenuActions { get; set; }
        public virtual DbSet<Sequence> Sequences { get; set; }
        public virtual DbSet<PAR> PARs { get; set; }
        public virtual DbSet<DepartmentUser> DepartmentUsers { get; set; }
        public virtual DbSet<AIRInvoice> AIRInvoices { get; set; }
        public virtual DbSet<RPCEFFOPPEItem> RPCEFFOPPEItems { get; set; }
        public virtual DbSet<RPCEFFOPPE> RPCEFFOPPEs { get; set; }
        public virtual DbSet<RSMI> RSMIs { get; set; }
        public virtual DbSet<Codextn> Codextns { get; set; }
        public virtual DbSet<PsCardItemUnitGroupDescription> PsCardItemUnitGroupDescriptions { get; set; }
        public virtual DbSet<PsCardItemIssuance> PsCardItemIssuances { get; set; }
        public virtual DbSet<RPCIDepLoc> RPCIDepLocs { get; set; }
        public virtual DbSet<CustodianDisposal> CustodianDisposals { get; set; }
        public virtual DbSet<CustodianDisposalItem> CustodianDisposalItems { get; set; }
        public virtual DbSet<DollarRate> DollarRates { get; set; }
        public virtual DbSet<CustodianReportItemIssuance> CustodianReportItemIssuances { get; set; }
        public virtual DbSet<ItemTypeExclusion> ItemTypeExclusions { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<LocationBudget> LocationBudgets { get; set; }
        public virtual DbSet<AIRItem> AIRItems { get; set; }
        public virtual DbSet<CustodianIirupItem> CustodianIirupItems { get; set; }
        public virtual DbSet<CustodianIIRUP> CustodianIIRUPs { get; set; }
        public virtual DbSet<PsCardItemTransaction> PsCardItemTransactions { get; set; }
        public virtual DbSet<PsCardItemUnitGroupDescriptionItem> PsCardItemUnitGroupDescriptionItems { get; set; }
        public virtual DbSet<AllField> AllFields { get; set; }
        public virtual DbSet<IcsPartUnitGroupDescription> IcsPartUnitGroupDescriptions { get; set; }
        public virtual DbSet<IcsParUnitGroupDescriptionItem> IcsParUnitGroupDescriptionItems { get; set; }
        public virtual DbSet<IcsParUnitGroup> IcsParUnitGroups { get; set; }
        public virtual DbSet<IcsPar> IcsPars { get; set; }
        public virtual DbSet<IcsParUpdate> IcsParUpdates { get; set; }
        public virtual DbSet<RPCIItem> RPCIItems { get; set; }
        public virtual DbSet<PsCardItemIssuanceItem> PsCardItemIssuanceItems { get; set; }
        public virtual DbSet<PsCardItemTransferItem> PsCardItemTransferItems { get; set; }
        public virtual DbSet<RpcPpe> RpcPpes { get; set; }
        public virtual DbSet<AIRItemExtn> AIRItemExtns { get; set; }
        public virtual DbSet<AIR> AIRs { get; set; }
        public virtual DbSet<PsCardItemTransferIssuanceItem> PsCardItemTransferIssuanceItems { get; set; }
        public virtual DbSet<PsCardItemExtn> PsCardItemExtns { get; set; }
        public virtual DbSet<AccountableOfficer> AccountableOfficers { get; set; }
        public virtual DbSet<PsCardItemExtnAddCost> PsCardItemExtnAddCosts { get; set; }
        public virtual DbSet<PsCard> PsCards { get; set; }
        public virtual DbSet<IcsParItem> IcsParItems { get; set; }
        public virtual DbSet<CustodianReportBldgItem> CustodianReportBldgItems { get; set; }
        public virtual DbSet<CustodianReportItem> CustodianReportItems { get; set; }
        public virtual DbSet<CustodianReportLandItem> CustodianReportLandItems { get; set; }
        public virtual DbSet<CustodianReportUpload> CustodianReportUploads { get; set; }
        public virtual DbSet<PsCardItemTransferIssuance> PsCardItemTransferIssuances { get; set; }
        public virtual DbSet<PsCardItemTransfer> PsCardItemTransfers { get; set; }
        public virtual DbSet<AuditLogDetail> AuditLogDetails { get; set; }
        public virtual DbSet<PsCardItem> PsCardItems { get; set; }
        public virtual DbSet<TrackingItem> TrackingItems { get; set; }
        public virtual DbSet<Tracking> Trackings { get; set; }
        public virtual DbSet<CustodianReport> CustodianReports { get; set; }
        public virtual DbSet<CustodianReportSubmitForCount> CustodianReportSubmitForCounts { get; set; }
        public virtual DbSet<NotificationMessageStatu> NotificationMessageStatus { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationUser> NotificationUsers { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<RPCI> RPCIs { get; set; }
        public virtual DbSet<NotificationMessage> NotificationMessages { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<RPCIItemExtn> RPCIItemExtns { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<RpcPpeItemBuilding> RpcPpeItemBuildings { get; set; }
        public virtual DbSet<RpcPpeItemLand> RpcPpeItemLands { get; set; }
        public virtual DbSet<RpcPpeItem> RpcPpeItems { get; set; }
        public virtual DbSet<CustodianReportBldgItemPhas> CustodianReportBldgItemPhases { get; set; }
        public virtual DbSet<PsCardItemExtnVehicleRepair> PsCardItemExtnVehicleRepairs { get; set; }
        public virtual DbSet<PsCardItemUnitGroup> PsCardItemUnitGroups { get; set; }
        public virtual DbSet<RSMIItem> RSMIItems { get; set; }
        public virtual DbSet<RSMIRecap> RSMIRecaps { get; set; }
        public virtual DbSet<ItemCodeRequest> ItemCodeRequests { get; set; }
        public virtual DbSet<Procurement> Procurements { get; set; }
        public virtual DbSet<ProcurementItem> ProcurementItems { get; set; }
        public virtual DbSet<ProcurementUnitGroupDescription> ProcurementUnitGroupDescriptions { get; set; }
        public virtual DbSet<ProcurementUnitGroup> ProcurementUnitGroups { get; set; }
        public virtual DbSet<ProcurementUnitGroupDescriptionItem> ProcurementUnitGroupDescriptionItems { get; set; }
        public virtual DbSet<Upload> Uploads { get; set; }
        public virtual DbSet<RisItem> RisItems { get; set; }
        public virtual DbSet<RisItemUnitGroupDescription> RisItemUnitGroupDescriptions { get; set; }
        public virtual DbSet<RISs> RISses { get; set; }
        public virtual DbSet<RisItemUnitGroup> RisItemUnitGroups { get; set; }
        public virtual DbSet<OrderItemUnitGroupDescriptionItem> OrderItemUnitGroupDescriptionItems { get; set; }
        public virtual DbSet<OrderItemUnitGroupDescription> OrderItemUnitGroupDescriptions { get; set; }
        public virtual DbSet<OrderItemUnitGroup> OrderItemUnitGroups { get; set; }
        public virtual DbSet<RequestItemUnitGroupDescriptionItem> RequestItemUnitGroupDescriptionItems { get; set; }
        public virtual DbSet<RequestItemUnitGroupDescription> RequestItemUnitGroupDescriptions { get; set; }
        public virtual DbSet<RequestItemUnitGroup> RequestItemUnitGroups { get; set; }
        public virtual DbSet<PARItem> PARItems { get; set; }
        public virtual DbSet<RisItemUnitGroupDescriptionItem> RisItemUnitGroupDescriptionItems { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<ItemCode> ItemCodes { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<RequestItem> RequestItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    }
}
