//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppManEntities : DbContext
    {
        public AppManEntities()
            : base("name=AppManEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menubase> Menubases { get; set; }
        public virtual DbSet<AspNetUserRoles_View> AspNetUserRoles_View { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserCodes_View> UserCodes_View { get; set; }
        public virtual DbSet<UserCode> UserCodes { get; set; }
        public virtual DbSet<UserInfo> UserInfos { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<AspNetUsers_View> AspNetUsers_View { get; set; }
        public virtual DbSet<CodeMast> CodeMasts { get; set; }
        public virtual DbSet<MenuAccess> MenuAccesses { get; set; }
        public virtual DbSet<MenuAccessAction> MenuAccessActions { get; set; }
        public virtual DbSet<MenuAction> MenuActions { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Sequence> Sequences { get; set; }
        public virtual DbSet<AIRItem> AIRItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Codextn> Codextns { get; set; }
        public virtual DbSet<Upload> Uploads { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<RISs> RISses { get; set; }
        public virtual DbSet<AIR> AIRs { get; set; }
        public virtual DbSet<PAR> PARs { get; set; }
        public virtual DbSet<OrderItemExtn> OrderItemExtns { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<ItemField> ItemFields { get; set; }
        public virtual DbSet<RisItem> RisItems { get; set; }
        public virtual DbSet<RequestItem> RequestItems { get; set; }
        public virtual DbSet<PsCode> PsCodes { get; set; }
        public virtual DbSet<PsStockExtn> PsStockExtns { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<PARItem> PARItems { get; set; }
        public virtual DbSet<AIRInvoice> AIRInvoices { get; set; }
        public virtual DbSet<RSMI> RSMIs { get; set; }
        public virtual DbSet<RSMIItem> RSMIItems { get; set; }
        public virtual DbSet<RSMIRecap> RSMIRecaps { get; set; }
        public virtual DbSet<RisIssued> RisIssueds { get; set; }
        public virtual DbSet<DepartmentUser> DepartmentUsers { get; set; }
        public virtual DbSet<PsItem> PsItems { get; set; }
        public virtual DbSet<ItemCode> ItemCodes { get; set; }
        public virtual DbSet<RisItemExtn> RisItemExtns { get; set; }
        public virtual DbSet<PsStock> PsStocks { get; set; }
        public virtual DbSet<RisItemUnitGroupDescriptionItem> RisItemUnitGroupDescriptionItems { get; set; }
        public virtual DbSet<RisItemUnitGroupDescription> RisItemUnitGroupDescriptions { get; set; }
        public virtual DbSet<RisItemUnitGroup> RisItemUnitGroups { get; set; }
    }
}
