//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers_View
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string UserId { get; set; }
        public string NameLast { get; set; }
        public string NameFirst { get; set; }
        public string NameMid { get; set; }
        public string NameFull { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Sex { get; set; }
        public string TelNo { get; set; }
        public string MobileNo { get; set; }
        public string AddressHouseNo { get; set; }
        public string AddressStreet { get; set; }
        public string AddressSubdivision { get; set; }
        public string AddressBarangay { get; set; }
        public string AddressCity { get; set; }
        public string AddressProvince { get; set; }
        public string AddressZipCode { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string UserName { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string Section { get; set; }
        public string UserCode { get; set; }
        public bool Active { get; set; }
    }
}
