//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ConversationId { get; set; }
        public string SenderId { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
        public string Text { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
