//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodianReportLandItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustodianReportLandItem()
        {
            this.CustodianDisposalItems = new HashSet<CustodianDisposalItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ReportId { get; set; }
        public string Fund { get; set; }
        public Nullable<decimal> CustodianItemNo { get; set; }
        public string SeriesNo { get; set; }
        public Nullable<bool> FromDonation { get; set; }
        public string Account { get; set; }
        public Nullable<System.Guid> ItemCodeId { get; set; }
        public string SubAccount { get; set; }
        public string Article { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public string LocationCode { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
        public string Condition { get; set; }
        public string Description { get; set; }
        public string SubLocation { get; set; }
        public string PIN { get; set; }
        public string Address { get; set; }
        public string LandMarks { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> PricePerSqm { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public string PsNo { get; set; }
        public string PropNo { get; set; }
        public string OldPropNo { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public Nullable<decimal> AcqCost { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public string Vendor { get; set; }
        public string Representative { get; set; }
        public string TctNo { get; set; }
        public string OldTctNo { get; set; }
        public string DRPNo { get; set; }
        public Nullable<System.DateTime> DRPDate { get; set; }
        public string OldDRPNo { get; set; }
        public Nullable<System.DateTime> OldDRPDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> CGT { get; set; }
        public Nullable<decimal> CGTTransferTax { get; set; }
        public Nullable<decimal> CGTSurcharge { get; set; }
        public Nullable<decimal> CGTInterest { get; set; }
        public Nullable<decimal> CGTCompromise { get; set; }
        public Nullable<decimal> DST { get; set; }
        public Nullable<decimal> DSTTransferTax { get; set; }
        public Nullable<decimal> DSTSurcharge { get; set; }
        public Nullable<decimal> DSTInterest { get; set; }
        public Nullable<decimal> DSTCompromise { get; set; }
        public Nullable<decimal> TransferTax { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> ConfirmationFee { get; set; }
        public Nullable<decimal> TransferRegsFee { get; set; }
        public Nullable<decimal> RealPropertyFee { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> EstateFee { get; set; }
        public Nullable<decimal> Titling { get; set; }
        public Nullable<decimal> CertificationFee { get; set; }
        public Nullable<decimal> Relocation { get; set; }
        public Nullable<decimal> Surveying { get; set; }
        public Nullable<decimal> IncidentalExpenses { get; set; }
        public string CapitalOutlayOrExpense { get; set; }
        public string Annex { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
    
        public virtual Codextn Codextn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianDisposalItem> CustodianDisposalItems { get; set; }
        public virtual CustodianReport CustodianReport { get; set; }
        public virtual ItemCode ItemCode { get; set; }
    }
}
