//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodianReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustodianReport()
        {
            this.CustodianReportBldgItems = new HashSet<CustodianReportBldgItem>();
            this.CustodianReportItems = new HashSet<CustodianReportItem>();
            this.CustodianReportLandItems = new HashSet<CustodianReportLandItem>();
            this.CustodianReportSubmitForCounts = new HashSet<CustodianReportSubmitForCount>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> AsOf { get; set; }
        public string Fund { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public string Department { get; set; }
        public string CertifiedCorrectBy { get; set; }
        public Nullable<int> AccountGroup { get; set; }
        public string ApprovedBy { get; set; }
        public string VerifiedBy { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianReportBldgItem> CustodianReportBldgItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianReportItem> CustodianReportItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianReportLandItem> CustodianReportLandItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianReportSubmitForCount> CustodianReportSubmitForCounts { get; set; }
        public virtual Codextn Codextn { get; set; }
    }
}
