//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodianReportBldgItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustodianReportBldgItem()
        {
            this.CustodianDisposalItems = new HashSet<CustodianDisposalItem>();
            this.CustodianReportBldgItemPhases = new HashSet<CustodianReportBldgItemPhas>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ReportId { get; set; }
        public string Fund { get; set; }
        public string CustodianItemNo { get; set; }
        public string SeriesNo { get; set; }
        public Nullable<bool> FromDonation { get; set; }
        public string Account { get; set; }
        public Nullable<System.Guid> ItemCodeId { get; set; }
        public string SubAccount { get; set; }
        public string Article { get; set; }
        public string Description { get; set; }
        public string BldgItem { get; set; }
        public string PoNo { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public Nullable<decimal> AcqCost { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public string Department { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public string LocationCode { get; set; }
        public string Location { get; set; }
        public string SubLocation { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public Nullable<int> AcqMonth { get; set; }
        public Nullable<int> AcqYear { get; set; }
        public Nullable<int> AcqDay { get; set; }
        public string Address { get; set; }
        public string ProjectName { get; set; }
        public string BuildingType { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> AppraiseValue { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public string PsNo { get; set; }
        public string PropNo { get; set; }
        public string PhaseNo { get; set; }
        public Nullable<decimal> PhaseAmountMooe { get; set; }
        public Nullable<decimal> PhaseAmountCo { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartDay { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> TargetYear { get; set; }
        public Nullable<int> TargetMonth { get; set; }
        public Nullable<int> TargetDay { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<decimal> PercentComplete { get; set; }
        public Nullable<int> CompletionYear { get; set; }
        public Nullable<int> CompletionMonth { get; set; }
        public Nullable<int> CompletionDay { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Status { get; set; }
        public string Condition { get; set; }
        public string Remarks { get; set; }
        public string Annex { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianDisposalItem> CustodianDisposalItems { get; set; }
        public virtual CustodianReportUpload CustodianReportUpload { get; set; }
        public virtual CustodianReport CustodianReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianReportBldgItemPhas> CustodianReportBldgItemPhases { get; set; }
        public virtual ItemCode ItemCode { get; set; }
        public virtual Codextn Codextn { get; set; }
        public virtual Codextn Codextn1 { get; set; }
    }
}
