//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodianDisposalItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CustodianDisposalId { get; set; }
        public Nullable<System.Guid> CustodianReportItemId { get; set; }
        public Nullable<System.Guid> CustodianReportLandItemId { get; set; }
        public Nullable<System.Guid> CustodianReportBldgItemId { get; set; }
        public string ArticleFields { get; set; }
        public string ArticleDisplay { get; set; }
        public Nullable<decimal> EstimatedKgMetals { get; set; }
        public Nullable<decimal> EstimatedKgOthers { get; set; }
        public Nullable<decimal> ReplCost { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<int> ServiceYear { get; set; }
        public Nullable<decimal> AccDep { get; set; }
        public Nullable<decimal> DisposalValue { get; set; }
        public Nullable<decimal> ValueKg { get; set; }
        public Nullable<decimal> FinalDisposalValue { get; set; }
        public Nullable<decimal> SalvageValue { get; set; }
        public Nullable<int> AcqYear { get; set; }
        public Nullable<int> EstLife { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<decimal> FinalReplCost { get; set; }
        public Nullable<decimal> AppraisalRate { get; set; }
        public Nullable<decimal> AcquisitionRate { get; set; }
        public Nullable<decimal> CFF { get; set; }
        public Nullable<decimal> CF { get; set; }
        public Nullable<decimal> UF { get; set; }
        public Nullable<int> AS_ { get; set; }
        public Nullable<int> L_AS { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<decimal> R_L { get; set; }
        public Nullable<decimal> RUV { get; set; }
        public Nullable<decimal> D { get; set; }
        public Nullable<decimal> AF { get; set; }
        public Nullable<decimal> V1 { get; set; }
        public Nullable<decimal> V2 { get; set; }
        public Nullable<decimal> V3 { get; set; }
        public Nullable<decimal> V4 { get; set; }
        public Nullable<int> Answer { get; set; }
        public Nullable<bool> ShowAcqMonth { get; set; }
        public Nullable<bool> ShowAcqDay { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual CustodianDisposal CustodianDisposal { get; set; }
        public virtual CustodianReportBldgItem CustodianReportBldgItem { get; set; }
        public virtual CustodianReportLandItem CustodianReportLandItem { get; set; }
        public virtual CustodianReportItem CustodianReportItem { get; set; }
    }
}
