//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodianReportUpload
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PsCardId { get; set; }
        public Nullable<System.Guid> PsCardItemId { get; set; }
        public Nullable<System.Guid> PsCardTransferId { get; set; }
        public Nullable<System.Guid> PsCardTransferItemId { get; set; }
        public Nullable<System.Guid> PsCardUnitGroupId { get; set; }
        public Nullable<System.Guid> PsCardUnitGroupDescriptionId { get; set; }
        public Nullable<System.Guid> PsCardUnitGroupDescriptionItemId { get; set; }
        public Nullable<System.Guid> PsCardItemExtnId { get; set; }
        public Nullable<System.Guid> IcsParId { get; set; }
        public Nullable<System.Guid> IcsParItemId { get; set; }
        public Nullable<System.Guid> IcsParUnitGroupId { get; set; }
        public Nullable<System.Guid> IcsParUnitGroupDescriptionId { get; set; }
        public Nullable<System.Guid> IcsParUnitGroupDescriptionItemId { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedDt { get; set; }
        public string DownloadedBy { get; set; }
        public Nullable<System.DateTime> DownloadedDt { get; set; }
    
        public virtual CustodianReportBldgItem CustodianReportBldgItem { get; set; }
        public virtual CustodianReportItem CustodianReportItem { get; set; }
        public virtual CustodianReportLandItem CustodianReportLandItem { get; set; }
    }
}
