//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodianDisposal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustodianDisposal()
        {
            this.CustodianDisposalItems = new HashSet<CustodianDisposalItem>();
            this.CustodianIirupItems = new HashSet<CustodianIirupItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public string Department { get; set; }
        public string TransmittalNo { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequestedDt { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
    
        public virtual Codextn Codextn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianDisposalItem> CustodianDisposalItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianIirupItem> CustodianIirupItems { get; set; }
    }
}
