//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodianReportBldgItemPhas
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> BldgItemId { get; set; }
        public string PhaseNo { get; set; }
        public Nullable<decimal> CapitalOutlay { get; set; }
        public Nullable<decimal> MOOE { get; set; }
        public string ProjectName { get; set; }
        public string BuildingType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<decimal> PercentComplete { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public Nullable<decimal> AcqCost { get; set; }
        public string Remarks { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual CustodianReportBldgItem CustodianReportBldgItem { get; set; }
    }
}
