//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodianIIRUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustodianIIRUP()
        {
            this.CustodianIirupItems = new HashSet<CustodianIirupItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> AsOf { get; set; }
        public string Chairman { get; set; }
        public string ChairmanTitle { get; set; }
        public string ViceChairman { get; set; }
        public string ViceChairmanTitle { get; set; }
        public string Member { get; set; }
        public string MemberTitle { get; set; }
        public string Officer { get; set; }
        public string OfficerTitle { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianIirupItem> CustodianIirupItems { get; set; }
    }
}
