//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustodianReportItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustodianReportItem()
        {
            this.CustodianDisposalItems = new HashSet<CustodianDisposalItem>();
            this.CustodianReportItemIssuances = new HashSet<CustodianReportItemIssuance>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ReportId { get; set; }
        public string Fund { get; set; }
        public string CustodianItemNo { get; set; }
        public string SeriesNo { get; set; }
        public Nullable<bool> FromDonation { get; set; }
        public string InvDist { get; set; }
        public string Account { get; set; }
        public Nullable<System.Guid> ItemCodeId { get; set; }
        public string SubAccount { get; set; }
        public string Article { get; set; }
        public string PoNo { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string AirNo { get; set; }
        public Nullable<System.DateTime> AirDate { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string Unit { get; set; }
        public string SetLotNo { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public string Department { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public string LocationCode { get; set; }
        public string Location { get; set; }
        public string SubLocation { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> TransferIn { get; set; }
        public Nullable<int> QtyBalance { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public string OldPsNo { get; set; }
        public string PsNo { get; set; }
        public string Description { get; set; }
        public string Brand { get; set; }
        public string Model_ { get; set; }
        public string Dimension { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
        public string Materials { get; set; }
        public string Capacity { get; set; }
        public string Color { get; set; }
        public string GenericName { get; set; }
        public string DosageStrength { get; set; }
        public string DosageForm { get; set; }
        public string DosageVolume { get; set; }
        public Nullable<int> Multipliers { get; set; }
        public string SerialNo { get; set; }
        public string OldPropNo { get; set; }
        public string PropNo { get; set; }
        public Nullable<int> YearModel { get; set; }
        public string PlateNo { get; set; }
        public string BodyNo { get; set; }
        public string MVFileNo { get; set; }
        public string EngineNo { get; set; }
        public string ChasisNo { get; set; }
        public string CRN { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string OrNo { get; set; }
        public Nullable<System.DateTime> OrDate { get; set; }
        public string InsPolicyNo { get; set; }
        public string ConductionNo { get; set; }
        public string ItemSerialNo { get; set; }
        public string OtherDesc { get; set; }
        public Nullable<int> OtherQty { get; set; }
        public string Condition { get; set; }
        public string Remarks { get; set; }
        public string ParNo { get; set; }
        public string ParIssuedTo { get; set; }
        public string AccountableOfficer { get; set; }
        public string AreNo { get; set; }
        public string AreIssuedTo { get; set; }
        public string AreOfficer { get; set; }
        public string MrNo { get; set; }
        public string MrIssuedTo { get; set; }
        public string MrOfficer { get; set; }
        public string IcsNo { get; set; }
        public string IcsIssuedTo { get; set; }
        public string IcsOfficer { get; set; }
        public string RpcPpeNo { get; set; }
        public string RpcPpeIssuedTo { get; set; }
        public string RpcPpeOfficer { get; set; }
        public string UpcomingPar { get; set; }
        public string UpcomingIcs { get; set; }
        public string Type { get; set; }
        public string Annex { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public Nullable<decimal> SetLotAmount { get; set; }
        public string SetLotRemarks { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public Nullable<decimal> ProRatedCost { get; set; }
        public Nullable<decimal> AddCost { get; set; }
        public Nullable<decimal> TUnitCost { get; set; }
        public Nullable<decimal> GTotalCost { get; set; }
    
        public virtual Codextn Codextn { get; set; }
        public virtual Codextn Codextn1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianDisposalItem> CustodianDisposalItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustodianReportItemIssuance> CustodianReportItemIssuances { get; set; }
        public virtual CustodianReportUpload CustodianReportUpload { get; set; }
        public virtual CustodianReport CustodianReport { get; set; }
        public virtual ItemCode ItemCode { get; set; }
    }
}
