//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentStatusHistory
    {
        public System.Guid Id { get; set; }
        public string DocumentType { get; set; }
        public System.Guid DocumentId { get; set; }
        public string DocumentNo { get; set; }
        public string FromStatus { get; set; }
        public string ToStatus { get; set; }
        public string Action { get; set; }
        public string Remarks { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangedDt { get; set; }
        public Nullable<int> ApprovalLevel { get; set; }
        public Nullable<System.Guid> ApprovingTeamId { get; set; }
    }
}
