//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentFieldReference
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EquipFieldId { get; set; }
        public Nullable<System.Guid> RefId { get; set; }
    
        public virtual EquipmentField EquipmentField { get; set; }
        public virtual PropertyCard PropertyCard { get; set; }
        public virtual RisItem RisItem { get; set; }
    }
}
