//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentField()
        {
            this.EquipmentFieldReferences = new HashSet<EquipmentFieldReference>();
        }
    
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string Model_ { get; set; }
        public string SerialNo { get; set; }
        public string Others { get; set; }
        public string Color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentFieldReference> EquipmentFieldReferences { get; set; }
    }
}
