//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public System.Guid Id { get; set; }
        public string ErrorSource { get; set; }
        public string ErrorCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
    }
}
