//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldsOther
    {
        public System.Guid Id { get; set; }
        public string Dimension { get; set; }
        public string Size { get; set; }
        public string Capacity { get; set; }
        public string Color { get; set; }
        public string Brand { get; set; }
        public string Model_ { get; set; }
    
        public virtual RisItem RisItem { get; set; }
        public virtual PsCard PsCard { get; set; }
    }
}
