//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldsVehicle
    {
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public string Make { get; set; }
        public string Series { get; set; }
        public Nullable<int> YearModel { get; set; }
        public string PlateNo { get; set; }
        public string BodyNo { get; set; }
        public string Color { get; set; }
        public string EngineNo { get; set; }
        public string ChassisNo { get; set; }
    
        public virtual PsCard PsCard { get; set; }
        public virtual RisItem RisItem { get; set; }
    }
}
