//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldsLand
    {
        public System.Guid Id { get; set; }
        public Nullable<decimal> Area { get; set; }
    
        public virtual PsCard PsCard { get; set; }
        public virtual RisItem RisItem { get; set; }
    }
}
