//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IcsParItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IcsParItem()
        {
            this.IcsParUnitGroupDescriptionItems = new HashSet<IcsParUnitGroupDescriptionItem>();
            this.PsCardItemTransferItems = new HashSet<PsCardItemTransferItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IcsParId { get; set; }
        public Nullable<System.Guid> PsCardItemExtnId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<System.Guid> PrevItemId { get; set; }
    
        public virtual PsCardItemExtn PsCardItemExtn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IcsParUnitGroupDescriptionItem> IcsParUnitGroupDescriptionItems { get; set; }
        public virtual IcsPar IcsPar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemTransferItem> PsCardItemTransferItems { get; set; }
    }
}
