//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IcsParUnitGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IcsParUnitGroup()
        {
            this.IcsPartUnitGroupDescriptions = new HashSet<IcsPartUnitGroupDescription>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IcsParId { get; set; }
        public string SetLotNo { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> AddCost { get; set; }
        public Nullable<decimal> TUnitCost { get; set; }
        public Nullable<decimal> GTotalCost { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IcsPartUnitGroupDescription> IcsPartUnitGroupDescriptions { get; set; }
        public virtual IcsPar IcsPar { get; set; }
    }
}
