//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IcsParItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IcsParId { get; set; }
        public Nullable<System.Guid> PsCardItemId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public string Location { get; set; }
        public string PropNo { get; set; }
        public string PropYear { get; set; }
        public string PropSeq { get; set; }
        public Nullable<decimal> AcqCost { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public string TctNo { get; set; }
        public string PhaseNo { get; set; }
        public Nullable<decimal> PhaseAmount { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> YearModel { get; set; }
        public string NetWeight { get; set; }
        public string ConductionSticker { get; set; }
        public string PlateNo { get; set; }
        public string BodyNo { get; set; }
        public string CRN { get; set; }
        public Nullable<System.DateTime> CRNDate { get; set; }
        public string MVFileNo { get; set; }
        public string DRPNo { get; set; }
        public Nullable<System.DateTime> DRPDate { get; set; }
        public Nullable<decimal> CGT { get; set; }
        public Nullable<decimal> CGTTransferTax { get; set; }
        public Nullable<decimal> CGTSurcharge { get; set; }
        public Nullable<decimal> CGTInterest { get; set; }
        public Nullable<decimal> CGTCompromise { get; set; }
        public Nullable<decimal> DST { get; set; }
        public Nullable<decimal> DSTTransferTax { get; set; }
        public Nullable<decimal> DSTSurcharge { get; set; }
        public Nullable<decimal> DSTInterest { get; set; }
        public Nullable<decimal> DSTCompromise { get; set; }
        public Nullable<decimal> TransferTax { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> ConfirmationFee { get; set; }
        public Nullable<decimal> TransferRegsFee { get; set; }
        public Nullable<decimal> RealPropertyTax { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> EstateTax { get; set; }
        public Nullable<decimal> Tilting { get; set; }
        public Nullable<decimal> CertificationFee { get; set; }
        public Nullable<decimal> Relocation { get; set; }
        public Nullable<decimal> Surveying { get; set; }
        public Nullable<decimal> IncidentalExpenses { get; set; }
        public string CapitalOutlayOrExpense { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual Codextn Codextn { get; set; }
        public virtual IcsPar IcsPar { get; set; }
        public virtual PsCardItem PsCardItem { get; set; }
    }
}
