//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IcsPar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IcsPar()
        {
            this.IcsParItems = new HashSet<IcsParItem>();
        }
    
        public System.Guid Id { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string RefType { get; set; }
        public string ReceivedBy { get; set; }
        public string ReceivedByPosition { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedDept { get; set; }
        public string IssuedBy { get; set; }
        public string IssuedByPosition { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string IssuedDept { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IcsParItem> IcsParItems { get; set; }
    }
}
