//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iLGSEntities : DbContext
    {
        public iLGSEntities()
            : base("name=iLGSEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menubase> Menubases { get; set; }
        public virtual DbSet<SysCode> SysCodes { get; set; }
        public virtual DbSet<AspNetUserRoles_View> AspNetUserRoles_View { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserCodes_View> UserCodes_View { get; set; }
        public virtual DbSet<UserCode> UserCodes { get; set; }
        public virtual DbSet<MenubaseAccess> MenubaseAccesses { get; set; }
        public virtual DbSet<UserInfo> UserInfos { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<AspNetUsers_View> AspNetUsers_View { get; set; }
        public virtual DbSet<Accessfile> Accessfiles { get; set; }
    }
}
