//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IssuedId { get; set; }
        public string RISNo { get; set; }
        public string RCCode { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual Issued Issued { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
