//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemCode()
        {
            this.PsCodes = new HashSet<PsCode>();
            this.RisItems = new HashSet<RisItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ItemTypeId { get; set; }
        public string ItemNo { get; set; }
        public string ItemNoIndex { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string ItemSw { get; set; }
        public string AccountCode { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCode> PsCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisItem> RisItems { get; set; }
        public virtual ItemType ItemType { get; set; }
    }
}
