//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenubaseAccess
    {
        public MenubaseAccess()
        {
            this.SubMenu = new HashSet<MenubaseAccess>();
        }
    
        public System.Guid AccessFileId { get; set; }
        public string SysCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int ChildId { get; set; }
        public string Description { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string ObjectParam { get; set; }
        public string MenuId { get; set; }
        public string ChildIdAccess { get; set; }
        public string ParentIdAccess { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<MenubaseAccess> SubMenu { get; set; }
        public virtual MenubaseAccess MainMenu { get; set; }
        public virtual Accessfile Accessfile { get; set; }
    }
}
