//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menubase
    {
        public Menubase()
        {
            this.SubMenu = new HashSet<Menubase>();
            this.Accessfiles = new HashSet<Accessfile>();
        }
    
        public string SysCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int ChildId { get; set; }
        public string Description { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string ObjectParam { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string MenuId { get; set; }
    
        public virtual SysCode SysCode1 { get; set; }
        public virtual ICollection<Menubase> SubMenu { get; set; }
        public virtual Menubase MainMenu { get; set; }
        public virtual ICollection<Accessfile> Accessfiles { get; set; }
    }
}
