//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItem()
        {
            this.AIRItems = new HashSet<AIRItem>();
            this.OrderItemUnitGroupDescriptionItems = new HashSet<OrderItemUnitGroupDescriptionItem>();
            this.PARItems = new HashSet<PARItem>();
            this.PsCardItems = new HashSet<PsCardItem>();
            this.RisItems = new HashSet<RisItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.Guid> RequestItemId { get; set; }
        public string ItemNo { get; set; }
        public string ItemNoIndex { get; set; }
        public Nullable<System.Guid> ItemCodeId { get; set; }
        public string PsNo { get; set; }
        public string PsNoDisplay { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public string Brand { get; set; }
        public Nullable<decimal> EstimatedLife { get; set; }
        public string Unit { get; set; }
        public string OtherDesc { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public Nullable<decimal> AddCost { get; set; }
        public Nullable<decimal> TUnitCost { get; set; }
        public Nullable<decimal> GTotalCost { get; set; }
        public string PpmpCode { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIRItem> AIRItems { get; set; }
        public virtual AllField AllField { get; set; }
        public virtual ItemCode ItemCode { get; set; }
        public virtual RequestItem RequestItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemUnitGroupDescriptionItem> OrderItemUnitGroupDescriptionItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARItem> PARItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItem> PsCardItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisItem> RisItems { get; set; }
        public virtual Order Order { get; set; }
    }
}
