//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSubItemRequest
    {
        public System.Guid Id { get; set; }
        public System.Guid OrderSubItemId { get; set; }
        public System.Guid RequestSubItemId { get; set; }
        public Nullable<decimal> QtyApplied { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual OrderSubItem OrderSubItem { get; set; }
        public virtual RequestSubItem RequestSubItem { get; set; }
    }
}
