//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.AIRs = new HashSet<AIR>();
            this.OrderItemUnitGroups = new HashSet<OrderItemUnitGroup>();
            this.PARs = new HashSet<PAR>();
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public System.Guid Id { get; set; }
        public string CtrlNo { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public string SupName { get; set; }
        public string SupBusiness { get; set; }
        public string SupAddress { get; set; }
        public string SupTIN { get; set; }
        public string SupEmail { get; set; }
        public string SupZipCode { get; set; }
        public string SupContactNo { get; set; }
        public string PoNo { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string PoMode { get; set; }
        public Nullable<System.Guid> PrId { get; set; }
        public string PrNo { get; set; }
        public Nullable<System.DateTime> PrDate { get; set; }
        public string Fund { get; set; }
        public string FPP { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public string DeliveryPlace { get; set; }
        public string DeliveryDate { get; set; }
        public string TermDelivery { get; set; }
        public string TermPayment { get; set; }
        public string SignedBySuppName { get; set; }
        public Nullable<System.DateTime> SignedBySuppDate { get; set; }
        public string SignedByAuthName { get; set; }
        public string SignedByAuthDesignation { get; set; }
        public string ResoNo { get; set; }
        public string CertifiedCorrectBy { get; set; }
        public Nullable<System.DateTime> CertifiedCorrectDate { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIR> AIRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemUnitGroup> OrderItemUnitGroups { get; set; }
        public virtual Request Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAR> PARs { get; set; }
        public virtual Codextn Codextn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
