//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementOrder : Procurement
    {
        public Nullable<System.Guid> SupplierId { get; set; }
        public string SupName { get; set; }
        public string SupBusiness { get; set; }
        public string SupAddress { get; set; }
        public string SupTIN { get; set; }
        public string SupEmail { get; set; }
        public string SupZipCode { get; set; }
        public string SupContactNo { get; set; }
        public string DeliveryPlace { get; set; }
        public string DeliveryDate { get; set; }
        public string TermDelivery { get; set; }
        public string TermPayment { get; set; }
        public string SignedBySuppName { get; set; }
        public Nullable<System.DateTime> SignedBySuppDate { get; set; }
        public string SignedByAuthName { get; set; }
        public string SignedByAuthDesignation { get; set; }
        public string ResoNo { get; set; }
        public string CertifiedCorrectBy { get; set; }
        public Nullable<System.DateTime> CertifiedCorredtDate { get; set; }
        public string PrNo { get; set; }
        public Nullable<System.DateTime> PrDate { get; set; }
    }
}
