//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementCartItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcurementCartItem()
        {
            this.ProcurementCartSubItems = new HashSet<ProcurementCartSubItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CartId { get; set; }
        public System.Guid PpmpItemId { get; set; }
        public Nullable<System.Guid> RequestItemId { get; set; }
        public string ItemNo { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string TechnicalSpecifications { get; set; }
        public string Unit { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ProcurementCart ProcurementCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcurementCartSubItem> ProcurementCartSubItems { get; set; }
    }
}
