//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementCartSubItem
    {
        public System.Guid Id { get; set; }
        public System.Guid CartItemId { get; set; }
        public Nullable<System.Guid> RequestSubItemId { get; set; }
        public string ItemNo { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ProcurementCartItem ProcurementCartItem { get; set; }
    }
}
