//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementRequest : Procurement
    {
        public string Purpose { get; set; }
        public string RequestedBy { get; set; }
        public string RequestedDesig { get; set; }
        public string Availability { get; set; }
        public string AvaliabilityDesig { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedDesig { get; set; }
    }
}
