//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procurement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procurement()
        {
            this.ProcurementItems = new HashSet<ProcurementItem>();
            this.ProcurementUnitGroups = new HashSet<ProcurementUnitGroup>();
        }
    
        public System.Guid Id { get; set; }
        public string RefType { get; set; }
        public string RefValue { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string Fund { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string FPP { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual Codextn Codextn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcurementItem> ProcurementItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcurementUnitGroup> ProcurementUnitGroups { get; set; }
    }
}
