//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementRISs : Procurement
    {
        public string Purpose { get; set; }
        public string RequestedBy { get; set; }
        public string RequestedByDesig { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedByDesig { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string IssuedBy { get; set; }
        public string IssuedByDesig { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string ReceivedBy { get; set; }
        public string ReceivedByDesig { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
    }
}
