//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyCard()
        {
            this.PropertyCardItems = new HashSet<PropertyCardItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ItemCodeId { get; set; }
        public string Fund { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public string PropNo { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string PrevPropNo { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public string AcqMode { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual ItemCode ItemCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyCardItem> PropertyCardItems { get; set; }
    }
}
