//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItemTransaction
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PsCardItemExtnId { get; set; }
        public Nullable<System.Guid> PsCardItemId { get; set; }
        public Nullable<System.Guid> PsCardItemIssuanceId { get; set; }
        public Nullable<System.Guid> PsCardItemTransferId { get; set; }
        public Nullable<System.Guid> IcsParId { get; set; }
        public string Remarks { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual IcsPar IcsPar { get; set; }
        public virtual PsCardItemExtn PsCardItemExtn { get; set; }
        public virtual PsCardItemIssuance PsCardItemIssuance { get; set; }
        public virtual PsCardItem PsCardItem { get; set; }
    }
}
