//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItemExtn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PsCardItemExtn()
        {
            this.PsCardItemIssuanceItems = new HashSet<PsCardItemIssuanceItem>();
            this.PsCardItemTransferItems = new HashSet<PsCardItemTransferItem>();
            this.RpcPpeItems = new HashSet<RpcPpeItem>();
            this.PsCardItemExtnAddCosts = new HashSet<PsCardItemExtnAddCost>();
            this.IcsParItems = new HashSet<IcsParItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> GroupId { get; set; }
        public Nullable<System.Guid> PsCardItemId { get; set; }
        public Nullable<System.Guid> AIRItemExtnId { get; set; }
        public string SetLotNo { get; set; }
        public Nullable<int> SetLotQtyNo { get; set; }
        public Nullable<int> ContentNo { get; set; }
        public string CustItemNo { get; set; }
        public Nullable<bool> IsAutoGen { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public string PropNo { get; set; }
        public string PropYear { get; set; }
        public string PropSeq { get; set; }
        public string SeriesNo { get; set; }
        public string Remarks { get; set; }
        public string Annex { get; set; }
        public string OldPropNo { get; set; }
        public string UpcomingOfficer { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string SubLocation { get; set; }
        public string Condition { get; set; }
        public Nullable<decimal> AddCost { get; set; }
        public Nullable<decimal> AcqCost { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
    
        public virtual AIRItemExtn AIRItemExtn { get; set; }
        public virtual Codextn Codextn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemIssuanceItem> PsCardItemIssuanceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemTransferItem> PsCardItemTransferItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RpcPpeItem> RpcPpeItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemExtnAddCost> PsCardItemExtnAddCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IcsParItem> IcsParItems { get; set; }
        public virtual PsCardItem PsCardItem { get; set; }
    }
}
