//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItemExtn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PsCardItemExtn()
        {
            this.IcsParItems = new HashSet<IcsParItem>();
            this.PsCardItemTransactions = new HashSet<PsCardItemTransaction>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PsCardItemId { get; set; }
        public Nullable<System.Guid> AIRItemExtnId { get; set; }
        public Nullable<int> ContentNo { get; set; }
        public Nullable<int> CustItemNo { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public string PropNo { get; set; }
        public string PropYear { get; set; }
        public string PropSeq { get; set; }
        public string SeriesNo { get; set; }
        public string Remarks { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual AIRItemExtn AIRItemExtn { get; set; }
        public virtual Codextn Codextn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IcsParItem> IcsParItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemTransaction> PsCardItemTransactions { get; set; }
        public virtual PsCardItem PsCardItem { get; set; }
    }
}
