//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItemExtnVehicleRepair
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PsCardItemExtnVehicleId { get; set; }
        public Nullable<System.DateTime> RepairDate { get; set; }
        public string InvoiceNo { get; set; }
        public string Nature { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AccTotal { get; set; }
        public Nullable<decimal> AccPercent { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual PsCardItemExtnVehicle PsCardItemExtnVehicle { get; set; }
    }
}
