//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItemExtnLand
    {
        public System.Guid Id { get; set; }
        public string PIN { get; set; }
        public string Address { get; set; }
        public string LandMarks { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public Nullable<decimal> PricePerSqm { get; set; }
        public Nullable<decimal> OldAmounts { get; set; }
        public string TctNo { get; set; }
        public string OldTctNo { get; set; }
        public string DRPNo { get; set; }
        public Nullable<System.DateTime> DRPDate { get; set; }
        public string OldDRPNo { get; set; }
        public Nullable<System.DateTime> OldDRPDate { get; set; }
        public Nullable<decimal> CGT { get; set; }
        public Nullable<decimal> CGTTransferTax { get; set; }
        public Nullable<decimal> CGTSurcharge { get; set; }
        public Nullable<decimal> CGTInteest { get; set; }
        public Nullable<decimal> CGTCompromise { get; set; }
        public Nullable<decimal> DST { get; set; }
        public Nullable<decimal> DSTTransferTax { get; set; }
        public Nullable<decimal> DSTSurcharge { get; set; }
        public Nullable<decimal> DSTInterest { get; set; }
        public Nullable<decimal> DSTCompromise { get; set; }
        public Nullable<decimal> TransferTax { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> ConfirmationFee { get; set; }
        public Nullable<decimal> TransferRegsFee { get; set; }
        public Nullable<decimal> RealPropertyTax { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> EstateTax { get; set; }
        public Nullable<decimal> Titling { get; set; }
        public Nullable<decimal> CerttificationFee { get; set; }
        public Nullable<decimal> Relocation { get; set; }
        public Nullable<decimal> Surveying { get; set; }
        public Nullable<decimal> IncidentalExpenses { get; set; }
        public string CapitalOutlayOrExpense { get; set; }
    
        public virtual PsCardItemExtn PsCardItemExtn { get; set; }
    }
}
