//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItemExtnLand : PsCardItemExtn
    {
        public string PIN { get; set; }
        public string Address { get; set; }
        public string LandMarks { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public Nullable<decimal> PricePerSqm { get; set; }
        public string TctNo { get; set; }
        public string OldTctNo { get; set; }
        public string DRPNo { get; set; }
        public Nullable<System.DateTime> DRPDate { get; set; }
        public string OldDRPNo { get; set; }
        public Nullable<System.DateTime> OldDRPDate { get; set; }
        public Nullable<decimal> CGT { get; set; }
        public Nullable<decimal> CGTTransferTax { get; set; }
        public Nullable<decimal> CGTSurcharge { get; set; }
        public Nullable<decimal> CGTInteest { get; set; }
        public Nullable<decimal> CGTCompromise { get; set; }
        public Nullable<decimal> DST { get; set; }
        public Nullable<decimal> DSTTransferTax { get; set; }
        public Nullable<decimal> DSTSurcharge { get; set; }
        public Nullable<decimal> DSTInterest { get; set; }
        public Nullable<decimal> DSTCompromise { get; set; }
        public Nullable<decimal> TransferTax { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> ConfirmationFee { get; set; }
        public Nullable<decimal> TransferRegsFee { get; set; }
        public Nullable<decimal> RealPropertyTax { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> EstateTax { get; set; }
        public Nullable<decimal> Titling { get; set; }
        public Nullable<decimal> CerttificationFee { get; set; }
        public Nullable<decimal> Relocation { get; set; }
        public Nullable<decimal> Surveying { get; set; }
        public Nullable<decimal> IncidentalExpenses { get; set; }
        public string CapitalOutlayOrExpense { get; set; }
        public Nullable<decimal> AreaXPrice { get; set; }
        public string Vendor { get; set; }
        public string Representative { get; set; }
        public Nullable<bool> CGTTransferTaxCap { get; set; }
        public Nullable<bool> CGTSurchargeCap { get; set; }
        public Nullable<bool> CGTInterestCap { get; set; }
        public Nullable<bool> CGTCompromiseCap { get; set; }
        public Nullable<bool> DSTTransferTaxCap { get; set; }
        public Nullable<bool> DSTSurchargeCap { get; set; }
        public Nullable<bool> DSTInterestCap { get; set; }
        public Nullable<bool> DSTCompromiseCap { get; set; }
        public Nullable<bool> TransferTaxCap { get; set; }
        public Nullable<bool> SurchargeCap { get; set; }
        public Nullable<bool> InterestCap { get; set; }
        public Nullable<bool> ConfirmationFeeCap { get; set; }
        public Nullable<bool> TransferRegsFeeCap { get; set; }
        public Nullable<bool> RealPropertyTaxCap { get; set; }
        public Nullable<bool> VATCap { get; set; }
        public Nullable<bool> EstateTaxCap { get; set; }
        public Nullable<bool> TitlingCap { get; set; }
        public Nullable<bool> CertificationFeeCap { get; set; }
        public Nullable<bool> RelocationCap { get; set; }
        public Nullable<bool> SurveyingCap { get; set; }
        public Nullable<bool> IncidentalExpensesCap { get; set; }
    }
}
