//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItemExtnVehicle : PsCardItemExtn
    {
        public Nullable<int> YearModel { get; set; }
        public string PlateNo { get; set; }
        public string BodyNo { get; set; }
        public string EngineNo { get; set; }
        public string ChasisNo { get; set; }
        public string Color { get; set; }
        public string CRN { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string MVFileNo { get; set; }
        public string OrNo { get; set; }
        public Nullable<System.DateTime> OrDate { get; set; }
        public Nullable<int> NetWeight { get; set; }
        public string InsPolicyNo { get; set; }
        public string ParReissuance { get; set; }
        public string ConductionNo { get; set; }
    }
}
