//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItemExtnBuilding
    {
        public System.Guid Id { get; set; }
        public string Address { get; set; }
        public string ProjectName { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PhaseAmountMooe { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> TargetYear { get; set; }
        public Nullable<int> TargetMonth { get; set; }
        public Nullable<decimal> PercentComplete { get; set; }
        public Nullable<int> CompletionYear { get; set; }
        public Nullable<int> CompletionMonth { get; set; }
        public string Status { get; set; }
        public string Condition { get; set; }
    
        public virtual PsCardItemExtn PsCardItemExtn { get; set; }
    }
}
