//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItemTransferIssuanceItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PsCardItemTransferIssuanceId { get; set; }
        public Nullable<System.Guid> PsCardItemTransferItemId { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual PsCardItemTransferItem PsCardItemTransferItem { get; set; }
        public virtual PsCardItemTransferIssuance PsCardItemTransferIssuance { get; set; }
    }
}
