//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PsCardItem()
        {
            this.PsCardItemExtns = new HashSet<PsCardItemExtn>();
            this.PsCardItemIssuances = new HashSet<PsCardItemIssuance>();
            this.PsCardItemTransactions = new HashSet<PsCardItemTransaction>();
            this.PsCardItemTransfers = new HashSet<PsCardItemTransfer>();
            this.PsCardItemUnitGroupDescriptionItems = new HashSet<PsCardItemUnitGroupDescriptionItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> GroupId { get; set; }
        public Nullable<System.Guid> PsCardId { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public Nullable<System.Guid> TransferRefId { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string PoNo { get; set; }
        public Nullable<System.DateTime> AirDate { get; set; }
        public string AirNo { get; set; }
        public Nullable<System.DateTime> AirIssueDate { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> QtyIss { get; set; }
        public Nullable<int> QtyBal { get; set; }
        public Nullable<int> TransferIn { get; set; }
        public Nullable<int> TransferOut { get; set; }
        public string TranType { get; set; }
        public Nullable<int> Days { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public string DeptDisplay { get; set; }
        public string Description { get; set; }
        public string OtherDesc { get; set; }
        public Nullable<bool> IsForICS { get; set; }
        public Nullable<bool> IsConsumable { get; set; }
        public Nullable<bool> IsIncorporated { get; set; }
        public Nullable<bool> IsOthers { get; set; }
        public string OtherRemarks { get; set; }
        public string Type { get; set; }
        public string InvDist { get; set; }
        public string AcqMode { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public Nullable<decimal> AreaSoldDonated { get; set; }
        public Nullable<int> ConstructionYear { get; set; }
        public string Vendor { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public Nullable<int> PhaseNo { get; set; }
        public Nullable<decimal> PhaseAmount { get; set; }
        public string PrevPsNo { get; set; }
        public string ParPostedBy { get; set; }
        public Nullable<System.DateTime> ParPostedDt { get; set; }
        public string SetLotNo { get; set; }
        public Nullable<decimal> SetLotAmount { get; set; }
        public string SetLotRemarks { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual Codextn Codextn { get; set; }
        public virtual Codextn Codextn1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemExtn> PsCardItemExtns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemIssuance> PsCardItemIssuances { get; set; }
        public virtual PsCardItemTransfer PsCardItemTransfer { get; set; }
        public virtual PsCard PsCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemTransaction> PsCardItemTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemTransfer> PsCardItemTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemUnitGroupDescriptionItem> PsCardItemUnitGroupDescriptionItems { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
