//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsCardItemExtnBuilding : PsCardItemExtn
    {
        public string Address { get; set; }
        public string ProjectName { get; set; }
        public string BuildingType { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> AppraisedValue { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PhaseAmountMooe { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<decimal> PercentComplete { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Status { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string BuildingItem { get; set; }
        public string PhaseNo { get; set; }
        public Nullable<decimal> PhaseAmountCo { get; set; }
    }
}
