//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PsItem()
        {
            this.RSMIRecaps = new HashSet<RSMIRecap>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PsStockId { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string RefType { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> QtyIss { get; set; }
        public Nullable<decimal> QtyBal { get; set; }
        public Nullable<int> Days { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSMIRecap> RSMIRecaps { get; set; }
        public virtual PsStock PsStock { get; set; }
    }
}
