//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsItemIssuance
    {
        public System.Guid Id { get; set; }
        public string TranCode { get; set; }
        public Nullable<System.Guid> PsItemId { get; set; }
        public Nullable<System.Guid> RisIssuedId { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string IssuedTo { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<System.Guid> SourceId { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual PsItem PsItem { get; set; }
    }
}
