//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PsStock()
        {
            this.PsItems = new HashSet<PsItem>();
            this.PsStockExtns = new HashSet<PsStockExtn>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PsId { get; set; }
        public string Fund { get; set; }
        public string StockNo { get; set; }
        public string StockName { get; set; }
        public string Description { get; set; }
        public string Brand { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual PsCode PsCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsItem> PsItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsStockExtn> PsStockExtns { get; set; }
    }
}
