//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Orders = new HashSet<Order>();
            this.RequestItems = new HashSet<RequestItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RisId { get; set; }
        public string Fund { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public string PrNo { get; set; }
        public Nullable<System.DateTime> PrDate { get; set; }
        public string FPP { get; set; }
        public string Purpose { get; set; }
        public string RequestedBy { get; set; }
        public string RequestedDesig { get; set; }
        public string Availability { get; set; }
        public string AvaialbilityDesig { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedDesig { get; set; }
        public string SubmittedBy { get; set; }
        public Nullable<System.DateTime> SubmittedDt { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual RISs RISs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestItem> RequestItems { get; set; }
    }
}
