//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RisItemPpe
    {
        public System.Guid RisItemId { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string Model_ { get; set; }
        public string SerialNo { get; set; }
        public string Others { get; set; }
        public string Color { get; set; }
    
        public virtual RisItem RisItem { get; set; }
    }
}
