//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RisItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RisItem()
        {
            this.RequestItems = new HashSet<RequestItem>();
            this.RisItemUnitGroupDescriptionItems = new HashSet<RisItemUnitGroupDescriptionItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RisId { get; set; }
        public Nullable<System.Guid> ItemCodeId { get; set; }
        public string SubAccountCode { get; set; }
        public string PsNo { get; set; }
        public string PsNoDisplay { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public string OtherDesc { get; set; }
        public string Unit { get; set; }
        public Nullable<int> QtyRequest { get; set; }
        public Nullable<int> QtyIssue { get; set; }
        public string Remarks { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual FieldsAccountableForm FieldsAccountableForm { get; set; }
        public virtual FieldsAgricultural FieldsAgricultural { get; set; }
        public virtual FieldsAnimal FieldsAnimal { get; set; }
        public virtual FieldsConstruction FieldsConstruction { get; set; }
        public virtual FieldsFurniture FieldsFurniture { get; set; }
        public virtual FieldsLand FieldsLand { get; set; }
        public virtual FieldsMachinery FieldsMachinery { get; set; }
        public virtual FieldsMedical FieldsMedical { get; set; }
        public virtual FieldsMedicine FieldsMedicine { get; set; }
        public virtual FieldsMilitarySuuply FieldsMilitarySuuply { get; set; }
        public virtual FieldsNonAccountableForm FieldsNonAccountableForm { get; set; }
        public virtual FieldsOfficeSupply FieldsOfficeSupply { get; set; }
        public virtual FieldsOther FieldsOther { get; set; }
        public virtual FieldsOtherSupplyMaterial FieldsOtherSupplyMaterial { get; set; }
        public virtual FieldsRepair FieldsRepair { get; set; }
        public virtual FieldsTransportation FieldsTransportation { get; set; }
        public virtual FieldsVehicle FieldsVehicle { get; set; }
        public virtual ItemCode ItemCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestItem> RequestItems { get; set; }
        public virtual RISs RISs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisItemUnitGroupDescriptionItem> RisItemUnitGroupDescriptionItems { get; set; }
    }
}
