//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RisIssued
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RisIssued()
        {
            this.PsCardItemIssuances = new HashSet<PsCardItemIssuance>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RisItemId { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public Nullable<System.Guid> OfficerId { get; set; }
        public string IssuedTo { get; set; }
        public string IssuedToPosition { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string IssuedBy { get; set; }
        public string IssuedByPosition { get; set; }
        public Nullable<System.DateTime> IssuedByDate { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string RefType { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public string PropNo { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual AccountableOfficer AccountableOfficer { get; set; }
        public virtual Codextn Codextn { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PsCardItemIssuance> PsCardItemIssuances { get; set; }
        public virtual RisItem RisItem { get; set; }
    }
}
