//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RISs()
        {
            this.Requests = new HashSet<Request>();
            this.RisItems = new HashSet<RisItem>();
        }
    
        public System.Guid Id { get; set; }
        public string Fund { get; set; }
        public string Division { get; set; }
        public string Office { get; set; }
        public string FPP { get; set; }
        public string RisNo { get; set; }
        public Nullable<System.DateTime> RisDate { get; set; }
        public string Purpose { get; set; }
        public string RequestedBy { get; set; }
        public string RequestedByDesignation { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedByDesignation { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string IssuedBy { get; set; }
        public string IssuedByDesignation { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string ReceivedBy { get; set; }
        public string ReceivedByDesignation { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RisItem> RisItems { get; set; }
    }
}
