//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPCEFFOPPEItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RpceffoppeId { get; set; }
        public string Article { get; set; }
        public string Description { get; set; }
        public string PropertyNo { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Location { get; set; }
        public string Condition { get; set; }
        public string Remarks { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual RPCEFFOPPE RPCEFFOPPE { get; set; }
    }
}
