//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RPCI()
        {
            this.RPCIDepLocs = new HashSet<RPCIDepLoc>();
            this.RPCIItems = new HashSet<RPCIItem>();
        }
    
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> AsOf { get; set; }
        public string Fund { get; set; }
        public Nullable<bool> FromDonation { get; set; }
        public string InvDist { get; set; }
        public Nullable<System.Guid> ItemTypeId { get; set; }
        public string Account { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public string Department { get; set; }
        public string CertifiedCorrectBy { get; set; }
        public string ApprovedBy { get; set; }
        public string VerifiedBy { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDt { get; set; }
        public Nullable<bool> IsPosted { get; set; }
    
        public virtual ItemType ItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPCIDepLoc> RPCIDepLocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPCIItem> RPCIItems { get; set; }
        public virtual Codextn Codextn { get; set; }
    }
}
