//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPCIItemExtn
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RpciItemId { get; set; }
        public Nullable<System.Guid> PsCardItemTransferItemId { get; set; }
        public Nullable<int> ContentNo { get; set; }
        public string CustItemNo { get; set; }
        public string PropNo { get; set; }
        public string Annex { get; set; }
        public string OldPropNo { get; set; }
        public string SeriesNo { get; set; }
        public Nullable<decimal> AcqCost { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public string SerialNo { get; set; }
        public string Condition { get; set; }
        public string Remarks { get; set; }
    
        public virtual RPCIItem RPCIItem { get; set; }
    }
}
