//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RpcPpe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RpcPpe()
        {
            this.RpcPpeItems = new HashSet<RpcPpeItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> AccountGroup { get; set; }
        public Nullable<System.DateTime> AsOf { get; set; }
        public string Fund { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public string Department { get; set; }
        public string CertifiedCorrectBy { get; set; }
        public string CertifiedCorrectDesignation { get; set; }
        public string ApprovedBy { get; set; }
        public string ApprovedDesignation { get; set; }
        public string VerifiedBy { get; set; }
        public string VerifiedDesignation { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDt { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual Codextn Codextn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RpcPpeItem> RpcPpeItems { get; set; }
    }
}
