//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RpcPpeItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RpcPpeId { get; set; }
        public string Fund { get; set; }
        public string Account { get; set; }
        public string Article { get; set; }
        public string SubArticle { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string Model_ { get; set; }
        public string SerialNo { get; set; }
        public string Others { get; set; }
        public string Color { get; set; }
        public string PropNo { get; set; }
        public string OldPropNo { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public string ActMode { get; set; }
        public string Location { get; set; }
        public string IssuedTo { get; set; }
        public string RefNo { get; set; }
        public string RefType { get; set; }
        public string Officer { get; set; }
        public string OldOfficer { get; set; }
        public string Condition { get; set; }
        public string Remarks { get; set; }
        public string Annex { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual RpcPpe RpcPpe { get; set; }
    }
}
