//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSMIItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RsmiId { get; set; }
        public Nullable<System.Guid> RisIssuedId { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
    
        public virtual RSMI RSMI { get; set; }
        public virtual RisIssued RisIssued { get; set; }
    }
}
