//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSMIItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RsmiId { get; set; }
        public string RisNo { get; set; }
        public string PoNo { get; set; }
        public string Department { get; set; }
        public string RCC { get; set; }
        public string LocationCode { get; set; }
        public string Location { get; set; }
        public string ItemCode { get; set; }
        public string StockNo { get; set; }
        public string ItemName { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AccountCode { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual RSMI RSMI { get; set; }
    }
}
