//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockItem()
        {
            this.StockItemIssuances = new HashSet<StockItemIssuance>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CardId { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string RefNo { get; set; }
        public string RefType { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> QtyIss { get; set; }
        public Nullable<int> QtyBal { get; set; }
        public Nullable<int> Days { get; set; }
        public string Remarks { get; set; }
        public string UnitMeas { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual StockCard StockCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItemIssuance> StockItemIssuances { get; set; }
    }
}
