//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockCard()
        {
            this.StockItems = new HashSet<StockItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ItemCodeId { get; set; }
        public string Fund { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public string StockNo { get; set; }
        public string StockName { get; set; }
        public Nullable<decimal> ReorderPoint { get; set; }
        public string PrevStockNo { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public string AcqMode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string GenericName { get; set; }
        public string DosageStrength { get; set; }
        public string DosageForm { get; set; }
        public string Brand { get; set; }
        public string Model_ { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItem> StockItems { get; set; }
        public virtual ItemCode ItemCode { get; set; }
    }
}
