//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAccountView
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ItemTypeId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string SubAccount { get; set; }
        public string Account { get; set; }
    }
}
