//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysCode
    {
        public SysCode()
        {
            this.Menubases = new HashSet<Menubase>();
        }
    
        public string SysCode1 { get; set; }
        public string SysDescription { get; set; }
        public string Insertedby { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual ICollection<Menubase> Menubases { get; set; }
    }
}
