//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingItem
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TrackingId { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public Nullable<System.DateTime> CheckInDt { get; set; }
        public string CheckInBy { get; set; }
        public Nullable<System.DateTime> CheckOutDt { get; set; }
        public string CheckOutBy { get; set; }
        public Nullable<System.DateTime> ReturnDt { get; set; }
        public string ReturnBy { get; set; }
    
        public virtual Tracking Tracking { get; set; }
        public virtual Codextn Codextn { get; set; }
    }
}
