//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iLgs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string RecId { get; set; }
        public Nullable<int> Ownership { get; set; }
        public string UserId { get; set; }
        public string Title { get; set; }
        public string NameCorporate { get; set; }
        public string NameFirst { get; set; }
        public string NameLast { get; set; }
        public string NameMid { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Street { get; set; }
        public string ZipCode { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public Nullable<System.DateTime> InsertedDt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
